import javax.swing.*;
import java.awt.*;
import java.awt.geom.*;

public class PieChart extends JPanel {
    private double[] values;
    private String[] labels;
    private Color[] colours;

    public PieChart(double[] values, String[] labels, Color[] colours){
        this.values = values;
        this.labels = labels;
        this.colours = colours;
    }

    public void updatePieChart(double[] values, String[] labels, Color[] colours) {
        this.values = values;
        this.labels = labels;
        this.colours = colours;
    }

    @Override
    protected void paintComponent(Graphics g) {
        // Code generated by ChatGPT
        // PROMPT: "Create a pie chart in java swing"
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;

        int width = getWidth();
        int height = getHeight();
        int minDim = Math.min(width, height);
        int pieDiameter = (int) (minDim * 0.9);
        int x = (width - pieDiameter) / 2;
        int y = (height - pieDiameter) / 2;

        double total = 0.0;
        for (double value : values) {
            total += value;
        }

        double startAngle = 0.0;
        for (int i = 0; i < values.length; i++) {
            double extent = 360.0 * (values[i] / total);
            g2d.setColor(colours[i]);
            g2d.fill(new Arc2D.Double(x, y, pieDiameter, pieDiameter, startAngle, extent, Arc2D.PIE));
            startAngle += extent;
        }

        int legendX = x + pieDiameter + 20;
        int legendY = y;
        int legendWidth = 100;
        int legendHeight = 20;

        for (int i = 0; i < labels.length; i++) {
            g2d.setColor(colours[i]);
            g2d.fillRect(legendX, legendY + i * (legendHeight + 5), legendWidth, legendHeight);
            g2d.setColor(Color.BLACK);
            g2d.drawString(labels[i], legendX + legendWidth + 5, legendY + i * (legendHeight + 5) + legendHeight / 2);
        }
    }
}
